### ISSUE TITLE
No License

### ISSUE THREAD

**Issue by pmclanahan** [keningle/pelican-sundown#2]
I'd like to use this one and modify it for my needs, but without a license specified I'm unsure what I can do. If you're unsure about FOSS licensing http://choosealicense.com/ may be of some help.

Thanks for this beautiful theme BTW!

**Comment by keningle** [comment]
Thanks for pointing this out, I am glad you like the theme.  I have now added a license (MIT license).  Mainly I want people to be able and use it for whatever they like, I hope you enjoy.

**Comment by pmclanahan** [comment]
Perfect. Thanks so much!
